### ISSUE TITLE
New insider_trading API keeps timing out

### ISSUE THREAD

**Issue by kpad-git** [daxm/fmpsdk#14]
The insider_trading function that was added recently was working fine a few days ago. Today when I ran it, it always times out with this message:

ERROR:root:Connection to https://financialmodelingprep.com/api/v4/insider-trading/ timed out.

What I am executing is fmpsdk.insider_trading(api_key, "MSFT", limit=100).

I am running code that sleeps for 1 second after every 8 calls to this API. And if I switch to other calls like balance_sheet_statement etc, those always work.

**Comment by kpad-git** [comment]
It just started working again... any ideas on what the right limit is for calls per second to avoid timeouts?

**Comment by antoinevulcain** [comment]
@kpad-git hello, it was on our side we are working on it

**Comment by antoinevulcain** [comment]
It should be back to normal now let me know if you see the timeout again

**Comment by ipl31** [comment]
@kpad-git when you see a connection time out raised from the sdk it is typically a failure on the API side, but it could also be something else like a network error. When I see this error I will typically go to the web page for the API docs and try the endpoint through my browser to see what the status is.

**Comment by kpad-git** [comment]
Ok thanks for the quick reply.  Looks like it is working again.
