### ISSUE TITLE
Looking for data: growth of Tangible Book Value per Share of a company. 

### ISSUE THREAD

**Issue by upenr** [daxm/fmpsdk#15]
Is this data available? 
Either tangible book value per share for every one of last five years, or tangible book value growth TTM or for each year.

**Comment by daxm** [comment]
At the moment this project, fmpsdk, is only mirroring what the FMP API 
offers.  I'm not sure whether we will get into custom (i.e. calculated 
from existing FMP API data) functions.  That said, I don't know if 
tangible book value growth is available from FMP's API.  If it does I'll 
be happy to add it if (if we don't already have it).

**Comment by upenr** [comment]
No, they didn't have `tangibleBookValueGrowth` either. They have tangible book value per share (TTM), but that's not what I was after. But thanks for letting me know.
