### ISSUE TITLE
A way to respect the limit of # request per minute

### ISSUE THREAD

**Issue by rickyking** [daxm/fmpsdk#16]
Hi,

Thanks for the great SDK.

I wonder whether the SDK is able to control the limit of request per minute to avoid API limitation?

Thanks

**Comment by daxm** [comment]
I do not have a paid account however I know that I've sent too many queries on occasion.  The occasions are rare but it does happen.

I'm sure there are methods of optimization (like parallelizing the queries) but that is beyond my programming skill at the moment.
:-)

**Comment by rickyking** [comment]
Yes I did do the multiprocessing. Anyway you are right need to figure out on my own. 

Thanks for building this.
