### ISSUE TITLE
control number of API calls per minute

### ISSUE THREAD

**Issue by simpsus** [daxm/fmpsdk#19]
with some plans there is a call/minute limit.
Is there a way to control that the requests are routed to the API "slow" enough to stay within a limit?
If not, do you plan on incorporating such a feature in the future?

Thx & best

**Comment by daxm** [comment]
We do not plan on implementing, at this time, something like that.  Our goal is to just provide a Python SDK to access the FMP APIs.  That said, we aren't against the idea so long as it doesn't adversely affect the use of fmpsdk.
I'd suggest you write into your Python script the limiter.

**Comment by simpsus** [comment]
Thank you very much.
Would you in principle be open to a PR for that functionality?
I noticed that the current architecture does not feature a API-entity at all, so it probably would go a long way from what there currently is ...

**Comment by daxm** [comment]
I'm not against it so long as it isn't a breaking change to what people are using/doing today.
