### ISSUE TITLE
How do I get minute data?

### ISSUE THREAD

**Issue by nectario** [daxm/fmpsdk#2]
How do I get minute data using the Python API?

**Comment by daxm** [comment]
There are several API calls that allow you to set the historical time you wish to collect so I'm not sure which you are wanting.  That said, if you look at https://github.com/daxm/fmpsdk/blob/master/fmpsdk-example.py there are several examples of setting the "time_delta" value.

**Comment by nectario** [comment]
Yeap I saw that. But there is no example to pass from_date and to_date for minute data.

**Comment by daxm** [comment]
Can we pass that?  I don't see that in the documentation.  If so, I can add it to fmpsdk.

**Comment by daxm** [comment]
no response
