### ISSUE TITLE
There is no distinction between no data and an error in __return_json_v3

### ISSUE THREAD

**Issue by kosmitive** [daxm/fmpsdk#21]
Hey,

we want to use your library and we came across the problem that there is no possibility to distinguish between there is no data and there was an error thrown __return_json_v3. We need this for retrying. Or is there a possibility which I have overseen? Otherwise we would add it, and maybe we can merge back in this repository.

**Comment by daxm** [comment]
Yeah, error catching is definitely thin in this project.  I'd love to 
see what you come up with to resolve this!

**Comment by kosmitive** [comment]
No error handling, because it would actually introduce breaking changes. Here is a minimal change to support handling all errors (as once) outside of the function https://github.com/daxm/fmpsdk/pull/22.

**Comment by daxm** [comment]
PR merged
