### ISSUE TITLE
def available_efts(apikey: str)  has misspelling of etf

### ISSUE THREAD

**Issue by wwasilev** [daxm/fmpsdk#28]
Change def available_efts(apikey: str) to def available_etfs(apikey: str)

**Comment by daxm** [comment]
I don't see a difference in your example.  What am I missing here?

**Comment by wwasilev** [comment]
eFTs vs eTFs

**Comment by daxm** [comment]
LOL.  I stared and stared at this and didn't see it.  Let me figure out how to "fix" this without making a breaking change.

**Comment by wwasilev** [comment]
You did make me re-check like 5 times! Thanks!
