### ISSUE TITLE
Missing ETF Expense ratio API

### ISSUE THREAD

**Issue by adamcataldo** [daxm/fmpsdk#29]
Hi,

It doesn't look like this API includes the ETF Expense ratio API:

https://site.financialmodelingprep.com/developer/docs/etf-expense-ratio-api/

I'd be open to contributing this, assuming the process for adding a new endpoint isn't insanely painful.

**Comment by ipl31** [comment]
Its a V4 endpoint, so you will need to look at another V4 API implementation as an example: https://github.com/daxm/fmpsdk/blob/master/fmpsdk/alternative_data.py  I don't know if @daxm has any plans to do an update, I might get around to it in the next few weeks. But it should not be too hard if you are up for it.

**Comment by daxm** [comment]
I'd love to take on adding v4 API but I'm quite busy.  @ken, if you are 
up to it I'd encourage you to take it on.  :-)

**Comment by adamcataldo** [comment]
I'm happy to do it, if you're open to pull requests. The code looks straightforward. Two questions:

1. I don't see tests, is that right? I want to make sure I'm not missing a requirements somewhere.
2. What's the release process? I see the [deploy_a_release.sh](https://github.com/daxm/fmpsdk/blob/master/deploy_a_release.sh) script, but I'm not sure if I can just run that (or if I even should), because I'm not sure what permissions are needed.

**Comment by daxm** [comment]
I'll do the deploy as it is in my pypi account.

I don't know how to do tests (that is why they don't exist). feel free 
to set that up if you'd like.  :-)  My "tests" are in the example script 
where I tried to list a "test" for each API call.

**Comment by adamcataldo** [comment]
I submitted a pull request. I think setting up the tests is a bigger effort, because you'd probably want to create a fake API that reads a JSON file representing an expected server response and returns that where the FMP server is expected. You'd then you'd need to modularize the functionality in [url_methods.py](https://github.com/daxm/fmpsdk/blob/master/fmpsdk/url_methods.py) so that tests use the fake service while non-tests use the real service. If you're interested in this, you might be able to persuade me to create the basic setup and a test for say this method, but adding tests for each end-point would probably take quite some time.
