### ISSUE TITLE
insider_trading function not in fmpsdk?

### ISSUE THREAD

**Issue by kpad-git** [daxm/fmpsdk#3]
I don't see the insider_trading function in the python sdk. Is this a known issue? Are there any plans to add it?

**Comment by daxm** [comment]
I'm sure it is possible.  I either missed adding it or FMP added it recently.  Let me find time to do this.

**Comment by ipl31** [comment]
I took a crack at adding this here https://github.com/ipl31/fmpsdk/tree/insider_trading but realized that it is on the V4 API endpoint. FMPSDK needs to support multiple version endpoints before it can be easily added. Will open a ticket for that.

**Comment by daxm** [comment]
I have added the API endpoints listed in the Insider Trading section of the FMP API documentation.  Granted, I didn't test them but I believe they will work.  Feel free to test and fix as you wish.  :-)
