### ISSUE TITLE
historical_price_full error with more than one symbol

### ISSUE THREAD

**Issue by paulhwatson** [daxm/fmpsdk#32]
Hi guys
Getting a key error when passing a list of 2 or 3 symbols to 'historical_price_full'. The same result happens using your samples.
Any suggestions

KeyError: 'historical'

**Comment by krazykoder** [comment]
Similar issue. I am getting this error. However for single stock it works. 

```
fmpsdk.historical_price_full(apikey=apikey, symbol=["AAL","GOOG"])

  File "/home/XXXX/venv3/lib/python3.9/site-packages/fmpsdk/general.py", line 96, in historical_price_full
    return res["historical"]
KeyError: 'historical'

```

**Comment by daxm** [comment]
I believe I was able to solve this issue.  We get a different JSON layout when multiple tickers are sent.  Created a new fmpsdk version.

**Comment by paulhwatson** [comment]
Hey thanks guys. Makes things more efficient. 😊On 23 Jun 2023, at 3:16 pm, daxm ***@***.***> wrote:﻿
I believe I was able to solve this issue.  We get a different JSON layout when multiple tickers are sent.  Created a new fmpsdk version.
