### ISSUE TITLE
Fork and update

### ISSUE THREAD

**Issue by Neuro17** [daxm/fmpsdk#33]
Hi @daxm . I'm using this module for quite some time and it's great. Since has not been updated with the latest endpoints I'd like to fork and start working on updating and then mainaining an updated version. 

Is there a problem in doing this?

**Comment by daxm** [comment]
You are welcome to do this as it is "free" software.  However, if you 
just maintain your fork then others using the current one won't get your 
updates.  I'd suggest you fork, update, and then issue a Pull Request 
(PR).  I can then update this repo and deploy a new release to pypi.
