### ISSUE TITLE
Historical Rating Function Pointing to Incorrect Endpoint

### ISSUE THREAD

**Issue by iguy0** [daxm/fmpsdk#34]
Hello,

Thank you for this great tool, very useful! I believe the historical_rating function in /fmpsdk/company_valuation.py may be pointing to the wrong API endpoint.

Please see below. 

```
def historical_rating(
    apikey: str,
    symbol: str,
    limit: int = DEFAULT_LIMIT,
) -> typing.Optional[typing.List[typing.Dict]]:
    """
    Query FMP /financial-growth/ API.
    :param apikey: Your API key.
    :param symbol: Company ticker.
    :param limit: Number of rows to return.
    :return: A list of dictionaries.
    """
    path = f"financial-growth/{symbol}"
    query_vars = {"apikey": apikey, "limit": limit}
    return __return_json_v3(path=path, query_vars=query_vars)
```

**Comment by iguy0** [comment]
I took a look and found the correct string. This is working for me:

`def historical_rating(
    apikey: str,
    symbol: str,
    limit: int = DEFAULT_LIMIT,
) -> typing.Optional[typing.List[typing.Dict]]:
    """
    Query FMP /historical-rating/ API.

    :param apikey: Your API key.
    :param symbol: Company ticker.
    :param limit: Number of rows to return.
    :return: A list of dictionaries.
    """
    path = f"historical-rating/{symbol}"
    query_vars = {"apikey": apikey, "limit": limit}
    return __return_json_v3(path=path, query_vars=query_vars)`

**Comment by iguy0** [comment]
I appreciate your prompt response earlier =] Like i mentioned, great job with the Lib!

**Comment by daxm** [comment]
Updated and new version released.
