### ISSUE TITLE
Implementation and documentation of historical-price-full and historical-chart are wrong 

### ISSUE THREAD

**Issue by marsson** [daxm/fmpsdk#37]
As per site doumentation below,
image
![image](https://github.com/daxm/fmpsdk/assets/827323/88f27817-d3ff-458d-9b41-a9bc3facedc2)

The historical-chartendpoint has the path parameters timeframe and symbol, and the query parameteres from, to and from dates. The implementation does not care for to and from, restricting the usability of the tool.
![image](https://github.com/daxm/fmpsdk/assets/827323/19f94f1f-a701-44e1-bfe1-1d9408b964ee)

imagethe same happens with the historical-price-full endpoint where we have the wrong list of parameters and unhelpful documentation on the api...
I will fix and create a pull request if allowed.

**Comment by daxm** [comment]
Absolutely! Issue a PR and I'll review it.

**Comment by marsson** [comment]
I have finished the development locally. how do you want me to create the pull request? I think I have to be added as a contributor right?

**Comment by daxm** [comment]
The way I know to generate a PR is to fork the project into my own repository. Make my changes there and then issue a PR from there. I'm sure there are other ways but that's the way I know to do it.
