### ISSUE TITLE
Why not  put the code to get the apikey into the sdk？

### ISSUE THREAD

**Issue by goolulu** [daxm/fmpsdk#43]
like this
```
def income_statement(
    apikey: str,
    symbol: str,
    period: str = "annual",
    limit: int = DEFAULT_LIMIT,
    download: bool = False,
    filename: str = INCOME_STATEMENT_FILENAME,
) -> typing.Union[typing.List[typing.Dict], None]:
    if apikey is None:
            apikey = os.environ.get("apikey")
    if apikey is None:
            raise someError()
    do_something()
```

1. Reduce the number of parameters that can be entered into the calling function
2. Reduce network requests

**Comment by daxm** [comment]
I see your point.  I didn't design it that way though.  :-(  It would take a lot of work (and breaking changes) to change it now.  This said, I'm not against redesigning in the future!  I've learned a lot about Session management in the requests module too and would like to use them here.

**Comment by daxm** [comment]
I'll close this issue if I don't hear further discussion on this topic on May 1st 2024.
