### ISSUE TITLE
How to get data for insider_trading in fmpsdk-example.py?

### ISSUE THREAD

**Issue by luweiming** [daxm/fmpsdk#51]
Hi There,

How to get data from from insider_trading? I ddint see insider_trading in fmpsdk-example.py file, but it's in a separated fmpsdk/insider_trading.py. 

I'm new to coding and apologize if this is a newbie question. Thanks.

**Comment by daxm** [comment]
The examples are just that; examples.  I was trying to show you how to use the various methods and functions.  However, other people have added to this project and we didn't continually updating the examples file.  Using your Python IDE you should be given enough information as to what is needed for the calls you wish to make.
