### ISSUE TITLE
Some of the type hints are off for default values

### ISSUE THREAD

**Issue by ShravanSunder** [daxm/fmpsdk#52]
An example is insider trading

```
def insider_trading(
    apikey: str,
    symbol: str = None,
    reporting_cik: int = None,
    company_cik: int = None,
    limit: int = DEFAULT_LIMIT,
) -> typing.Optional[typing.List[typing.Dict]]:
```

the above should be change to have `| None` to more representative types.  I'm using signatures to dynamically call the funciton, so its causing a bit of issues. 
```
def insider_trading(
    apikey: str,
    symbol: str | None= None,
    reporting_cik: int | None = None,
    company_cik: int | None = None,
    limit: int = DEFAULT_LIMIT,
) -> typing.Optional[typing.List[typing.Dict]]:
```

**Comment by daxm** [comment]
Can you issue a pull request for this?  Additionally, I'm looking for someone to help maintain this project as I'm no longer able to do it consistently.
